# Generated by Django 6.1 on 2026-08-19 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0003_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentLabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], max_length=255)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.appointment')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.labtest')),
            ],
        ),
    ]
