# Generated by Django 6.1 on 2026-08-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=255)),
                ('driver_name', models.CharField(max_length=255)),
                ('ambulance_type', models.CharField(choices=[('Basic Life Support', 'Basic Life Support'), ('Advanced Life Support', 'Advanced Life Support'), ('Patient Transport', 'Patient Transport')], max_length=255)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy')], max_length=255)),
            ],
        ),
    ]
